export const config = {
  API_URL: import.meta.env.VITE_BASE_API_URL,
  CLOUDINARY_UPLOAD_URL: import.meta.env.VITE_CLOUDINARY_UPLOAD_URL,
  CLOUDINARY_UPLOAD_PRESET: import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET
}
